server:
  port: 3344
spring:
  application:
    name: springcloud-study-config
  cloud:
    config:
      server:
        git:
          # uri: git@github.com:gongxings/springcloud-study-config.git
          uri: https://github.com/whale1998/microservicespringcloud-config.git
          search-paths: config-repo
          username:   #账号
          password:   #密码
